- deploy.md
- release-notes.md
- toc.md
Update to 1.4.1
Should be merged only after CE 1.4.1 is GA
> Update documentation for 1.4.1 patch release

- VMwarePub.yaml
- deploy.md
- release-notes.md
- toc.md
> doc changes for 1.4.2

- VMwarePub.yaml
- deploy.md
- release-notes.md
- toc.md
Please Merged on or after 30th June
> Updating 1.5 docs to 1.5.2

- deploy.md
- release-notes.md
GA for 1.6 is 6th July . this can be added to staging
> Adding 1.6 release notes

- VMwarePub.yaml
- deploy.md
- release-notes.md
- toc.md
> release docs for 1.3.1

- VMwarePub.yaml
- deploy.md
- release-notes.md
- toc.md
GA Date 31-Jul.
Please add to staging docs
> adding doc for CE 1.5.3

- VMwarePub.yaml
- deploy.md
- release-notes.md
- toc.md
Please check and add to staging docs.
GA date is 31-Jul
> adding docs for 1.4.3

- VMwarePub.yaml
- deploy.md
- release-notes.md
- toc.md
Docs for patch 1.3.2
Please review and merge to staging.
GA date 31-Jul
> adding docs for version 1.3.2

- VMwarePub.yaml
- deploy.md
- release-notes.md
- toc.md
@YugangW , please check and push to staging.
GA date is 8/31
> adding docs for 1.6.1

- VMwarePub.yaml
- deploy.md
- release-notes.md
- toc.md
Please review and merge and publish to staging.
GA date is 8/31
> docs for 1.5.4

- VMwarePub.yaml
- deploy.md
- release-notes.md
- toc.md
@YugangW Please review and merge and publish to staging
> docs for 1.4.4

- VMwarePub.yaml
- deploy.md
- release-notes.md
- toc.md
Please review and merge and publish to staging, @YugangW
> Docs for 1.3.3

- deploy.md
Adding the doc fix for K8s cluster where PSA is enforced
> Adding the doc fix for K8s cluster where PSA is enforced

- VMwarePub.yaml
- deploy.md
- release-notes.md
@YugangW Please review and deploy to staging
> Adding docs for CE 1.8.0

- deploy.md
Update supported platforms to indicate that only amd64 cpus are supported. 
To be cherry picked on to all CE versions.
> Update supported platforms

- deploy.md
- Updated doc for exporting CA_PATH to pull image and deploy kapp-controller using custom CA certificate
> Updated doc for exporting CA_PATH to install KC using custom CA certificate

- deploy.md
Fixing the troubleshooting step in 1.7
> Fixing the troubleshooting step in 1.7

- deploy.md
Fixing the troubleshooting step in 1.8
> Fixing the troubleshooting step in 1.8

- deploy.md
Updating documentation with new platform details
> [1.8] Updating documentation with new platform details

- deploy.md
Updating documentation with new platform details
> [1.7] Updating documentation with new platform details

- deploy.md
Updating documentation with new platform details
> [1.6] Updating documentation with new platform details

- deploy.md
> [1.9] Updating documentation

- deploy.md
> Making doc changes

- deploy.md
> Releasing docs for 1.9.1
